### ISSUE TITLE
HOW DO I INSTALL THIS

### ISSUE THREAD

**Issue by abue-ammar** [drivardxrm/ShieldsIO.Badge.PCF#1]
how do i install. there's nothing written. is there any exe file or what is this thing. no clear explanation

**Comment by drivardxrm** [comment]
Not sure I understand your comment... you know what a PCF control is right?

The first link on the readme points to the latest release,
I will kindly paste the link here for you again : https://github.com/drivardxrm/ShieldsIO.Badge.PCF/releases/latest

download the solution file (.zip) and install it in your Dataverse (PowerApps) environment
